declare module "lucide-react-native" {
  import { ComponentType } from "react";
  export interface IconProps {
    size?: number;
    color?: string;
    strokeWidth?: number;
    style?: any;
    fill?: string;
  }
  export const Search: ComponentType<IconProps>;
  export const Lock: ComponentType<IconProps>;
  export const Plus: ComponentType<IconProps>;
  export const Settings: ComponentType<IconProps>;
  export const KeyRound: ComponentType<IconProps>;
  export const CreditCard: ComponentType<IconProps>;
  export const FileText: ComponentType<IconProps>;
  export const User: ComponentType<IconProps>;
  export const MapPin: ComponentType<IconProps>;
  export const ChevronRight: ComponentType<IconProps>;
  export const Globe: ComponentType<IconProps>;
  export const Shield: ComponentType<IconProps>;
  export const Fingerprint: ComponentType<IconProps>;
  export const ArrowLeft: ComponentType<IconProps>;
  export const Copy: ComponentType<IconProps>;
  export const Check: ComponentType<IconProps>;
  export const Eye: ComponentType<IconProps>;
  export const EyeOff: ComponentType<IconProps>;
  export const Edit2: ComponentType<IconProps>;
  export const ShieldCheck: ComponentType<IconProps>;
  export const X: ComponentType<IconProps>;
  export const Save: ComponentType<IconProps>;
  export const Wand2: ComponentType<IconProps>;
  export const LogOut: ComponentType<IconProps>;
  export const Key: ComponentType<IconProps>;
  export const Mail: ComponentType<IconProps>;
  export const ArrowRight: ComponentType<IconProps>;
  export const RefreshCw: ComponentType<IconProps>;
  export const CheckCircle: ComponentType<IconProps>;
  export const CheckCircle2: ComponentType<IconProps>;
  export const Folder: ComponentType<IconProps>;
  export const Star: ComponentType<IconProps>;
  export const Trash2: ComponentType<IconProps>;
  export const ExternalLink: ComponentType<IconProps>;
  export const AlertCircle: ComponentType<IconProps>;
  export const Download: ComponentType<IconProps>;
  export const Upload: ComponentType<IconProps>;
  export const ShieldAlert: ComponentType<IconProps>;
  export const Clock: ComponentType<IconProps>;
  export const Monitor: ComponentType<IconProps>;
  export const Smartphone: ComponentType<IconProps>;
  export const Database: ComponentType<IconProps>;
  export const RotateCcw: ComponentType<IconProps>;
  export const Edit3: ComponentType<IconProps>;
  export const Pencil: ComponentType<IconProps>;
  export const CornerDownRight: ComponentType<IconProps>;
  export const FolderPlus: ComponentType<IconProps>;
  export const FolderOpen: ComponentType<IconProps>;
  export const LogIn: ComponentType<IconProps>;
  export const History: ComponentType<IconProps>;
  export const ChevronDown: ComponentType<IconProps>;
  export const Inbox: ComponentType<IconProps>;
  export const Keyboard: ComponentType<IconProps>;
  export const Sparkles: ComponentType<IconProps>;
}
